version: "3.1"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 9000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: test
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:9000
    ports:
      - 3000:3000
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    # Use volumes if you want to persist data
    # volumes:
    #   - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 5434:5434
